version: 0.2
env:
  variables:
    ECR_REPO: $$ACCOUNT_ID$$.dkr.ecr.$$AWS_REGION$$.amazonaws.com
phases:
  install:
    runtime-versions:
      docker: 19
  pre_build:
    commands:
  build:
    commands:
      # Create ECR for MS-STOCKS
      # TODO

      # Create ECR_REPO
      - ECR_REPO=$(echo "$ECR_REPO" | sed 's/\$\$AWS_REGION\$\$/'"${AWS_REGION}"'/g')
      - ECR_REPO=$(echo "$ECR_REPO" | sed 's/\$\$ACCOUNT_ID\$\$/'"${ACCOUNT_ID}"'/g')

      - echo Logging in to Amazon ECR...
      - aws --version
      - $(aws ecr get-login --region $AWS_DEFAULT_REGION --no-include-email)
      - COMMIT_HASH=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
      - IMAGE_TAG=${COMMIT_HASH:=latest}
      - echo $IMAGE_TAG

      # Build the Docker images
      - echo Building the production Docker image...
      # Stocks Microservice Image
      - docker build -t bevcapital-msstocks -f ./Dockerfile ./src
      - docker tag bevcapital-msstocks ${ECR_REPO}/bevcapital-msstocks:$IMAGE_TAG
      - docker tag bevcapital-msstocks ${ECR_REPO}/bevcapital-msstocks:latest

      # Nginx Daemon Image
      - docker build -t bevcapital-msstocks-nginx -f ./nginx/Dockerfile ./nginx
      - docker tag bevcapital-msstocks-nginx ${ECR_REPO}/bevcapital-msstocks-nginx:$IMAGE_TAG
      - docker tag bevcapital-msstocks-nginx ${ECR_REPO}/bevcapital-msstocks-nginx:latest

      # X-Ray Daemon Image
      - docker build -t bevcapital-msstocks-xray -f ./xray/Dockerfile ./xray
      - docker tag bevcapital-msstocks-xray ${ECR_REPO}/bevcapital-msstocks-xray:$IMAGE_TAG
      - docker tag bevcapital-msstocks-xray ${ECR_REPO}/bevcapital-msstocks-xray:latest

  post_build:
    commands:
      # Take these images and push them to ECR
      - echo Pushing the Docker images...
      - docker push ${ECR_REPO}/bevcapital-msstocks:latest
      - docker push ${ECR_REPO}/bevcapital-msstocks:$IMAGE_TAG

      - docker push ${ECR_REPO}/bevcapital-msstocks-nginx:latest
      - docker push ${ECR_REPO}/bevcapital-msstocks-nginx:$IMAGE_TAG

      - docker push ${ECR_REPO}/bevcapital-msstocks-xray:latest
      - docker push ${ECR_REPO}/bevcapital-msstocks-xray:$IMAGE_TAG

      # Generate json with service images endpoint
      - printf '{' >> serviceimages.json
      - printf ' "ServiceImageUrl":"%s", ' ${ECR_REPO}/bevcapital-msstocks:latest >> serviceimages.json
      - printf ' "NginxImageUrl":"%s", ' ${ECR_REPO}/bevcapital-msstocks-nginx:latest >> serviceimages.json
      - printf ' "XRayImageUrl":"%s" ' ${ECR_REPO}/bevcapital-msstocks-xray:latest >> serviceimages.json
      - printf '}' >> serviceimages.json
artifacts:
  files:
    - serviceimages.json
